spring:
  application.name: resource-server
  main.banner-mode: off
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:test}
            client-secret: ${GOOGLE_CLIENT_SECRET:test}
            scope: openid,profile,email

logging:
  level:
    org.springframework.security: debug